#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE="$SCRIPT_DIR/profiles/fix-protobuf"

mkdir -p "$(dirname "$PROFILE")"
cat > "$PROFILE" << 'EOF'
[replace_requires]
protobuf/*: protobuf/3.21.12

[replace_tool_requires]
protobuf/*: protobuf/3.21.12
ninja/*: ninja/1.13.2
EOF

rm -rf build
mkdir build
cd build

# Install the required dependency libraries in the file 'conanfile.txt'
conan install "$SCRIPT_DIR" --build=missing \
  -pr=default \
  -pr="$PROFILE"

# Load the environment script generated by Conan
CONAN_ENV="$(pwd)/Release/generators/conanbuild.sh"
if [ -f "$CONAN_ENV" ]; then
    echo "=== Load Conan environment ==="
    source "$CONAN_ENV"
else
    echo "❌ Error: $CONAN_ENV does not exist"
    exit 1
fi

echo ""
echo "=== Environment verification ==="
export PKG_CONFIG_PATH="$(pwd)/Release/generators"
echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
echo "PATH: $PATH"
which g++
which c++
echo ""

echo "=== Tool verification ==="
which meson ninja protoc
meson --version
ninja --version
protoc --version
echo ""

echo "=== pkg-config verification ==="
pkg-config --modversion protobuf-c
echo ""

echo "=== Start building ==="
meson setup . ..
meson compile