apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-sctp-server" (include "sctp-sig-gateway.fullname" .) }}
data:
  config.json: |
    {
      "log_level": "debug",
      "grpc": {
        "target_addr": "{{ printf "%s-sctp-client-grpc" (include "sctp-sig-gateway.fullname" .) }}:50051",
        "srv_addr": "0.0.0.0:50051"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-sctp-client" (include "sctp-sig-gateway.fullname" .) }}
data:
  config.json: |
    {
      "log_level": "debug",
      "grpc": {
        "target_addr": "{{ printf "%s-sctp-server-grpc" (include "sctp-sig-gateway.fullname" .) }}:50051",
        "srv_addr": "0.0.0.0:50051"
      }
    }